name: flutter_grocery
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^8.0.2
  provider: ^6.1.2
  http: ^0.13.1
  freezed: ^2.5.7
  shared_preferences: ^2.0.5
  photo_view: ^0.15.0
  dio: ^5.7.0
  image_picker: ^1.1.2
  pin_code_fields: ^8.0.1
  google_maps_flutter_web: ^0.5.10
  google_maps_flutter: ^2.0.3
  flutter_google_places: ^0.3.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  shimmer_animation: ^2.0.0
  url_launcher: ^6.0.2
  webview_flutter: ^4.10.0
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  path_provider: ^2.0.1
  flutter_html: ^3.0.0-beta.2
  connectivity: ^3.0.2
  carousel_slider: ^5.0.0
  fluro: ^2.0.3
  url_strategy: ^0.3.0
  universal_html: ^2.0.8
  flutter_widget_from_html_core: ^0.15.2
  phone_number: ^2.1.0
  country_code_picker: ^3.1.0
  flutter_typeahead: ^5.2.0
  flutter_overlay_loader: ^2.0.0
  google_maps_webservice: any
  connectivity_for_web: any
  firebase_core_web: any
  firebase_messaging_web: any
  flutter_keyboard_visibility_web: any
  geolocator_web: any
  image_picker_for_web: any
  package_info_plus_web: any
  shared_preferences_web: any
  url_launcher_web: any
  video_player_web: any
  wakelock_web: any
  collection: any
  modal_bottom_sheet: any
  universal_platform: any
  intl: any
  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700